import fs from 'fs';
import path from 'path';

const fixPackageJson = () => {
    const templatePath = path.resolve('templates/common/package.json.ejs');
    const content = `{
  "name": "<%= projectName %>",
  "version": "1.0.0",
  "description": "Generated by nodejs-quickstart",
  "main": "<% if (language === 'TypeScript') { %>dist/index.js<% } else { %>src/index.js<% } %>",
  "scripts": {
    "start": "<% if (language === 'TypeScript') { %>node dist/index.js<% } else { %>node src/index.js<% } %>",
    "dev": "<% if (language === 'TypeScript') { %>nodemon --exec ts-node src/index.ts<% } else { %>nodemon src/index.js<% } %>"<% if (language === 'TypeScript') { %>,
    "build": "rimraf dist && tsc"<% } %>
  },
  "dependencies": {
    "express": "^4.18.2",
    "dotenv": "^16.3.1",
    <% if (database === 'MySQL') { %>"mysql2": "^3.6.5",<% } %>
    <% if (database === 'PostgreSQL') { %>"pg": "^8.11.3",<% } %>
    <% if (communication === 'Kafka') { %>"kafkajs": "^2.2.4",<% } %>
    "cors": "^2.8.5"
  },
  "devDependencies": {
    "nodemon": "^3.0.2"<% if (language === 'TypeScript') { %>,
    "typescript": "^5.3.3",
    "ts-node": "^10.9.2",
    "@types/node": "^20.10.5",
    "@types/express": "^4.17.21",
    "@types/cors": "^2.8.17",
    "@types/dotenv": "^8.2.0",
    <% if (database === 'PostgreSQL') { %>"@types/pg": "^8.10.9",<% } %>
    "rimraf": "^5.0.5"<% } %>
  }
}`;
    fs.writeFileSync(templatePath, content, 'utf8');
    console.log('Fixed package.json.ejs');
};

const fixReadme = () => {
    const templatePath = path.resolve('templates/common/README.md.ejs');
    const content = `# <%= projectName %>

This project was generated using \`nodejs-quickstart-structure\`.

## Prerequisites

- Node.js (v18+)
- Docker & Docker Compose

## Getting Started

1.  **Start Infrastructure** (Database<% if (communication === 'Kafka') { %>, Kafka, Zookeeper<% } %>):
    \`\`\`bash
    docker-compose up -d
    \`\`\`

2.  **Install Dependencies**:
    \`\`\`bash
    npm install
    \`\`\`

3.  **Run Application**:
    \`\`\`bash
    npm run dev
    \`\`\`

## Project Structure

The project uses **<%= architecture %>** with **<%= database %>**.
<% if (communication === 'Kafka') { %>
Microservices communication handled via **Kafka**.
<% } else { %>
API is exposed via **REST**.
<% } %>

## Demo & Testing

### Health Check

\`\`\`bash
curl http://localhost:3000/health
# Output: {"status":"UP"}
\`\`\`

<% if (communication === 'REST APIs') { %>
### User API Demo

**Create a User:**
\`\`\`bash
curl -X POST http://localhost:3000/api/users \\
  -H "Content-Type: application/json" \\
  -d '{"name": "Alice", "email": "alice@example.com"}'
\`\`\`

**Get Users:**
\`\`\`bash
curl http://localhost:3000/api/users
\`\`\`
<% } %>

<% if (communication === 'Kafka') { %>
### Kafka
- **Zookeeper**: Port \`2181\`
- **Kafka Broker**: Port \`9092\`

You can connect to Kafka using the \`kafkajs\` library installed in the project.
<% } %>

## Database Migrations

**Flyway** is running in Docker and will automatically apply SQL migrations from \`flyway/sql/\` on startup.
`;
    fs.writeFileSync(templatePath, content, 'utf8');
    console.log('Fixed README.md.ejs');
};

fixPackageJson();
fixReadme();
