import fs from 'fs';
import path from 'path';

const fixPackageJson = () => {
    const templatePath = path.resolve('templates/common/package.json.ejs');
    const content = `{
  "name": "<%= projectName %>",
  "version": "1.0.0",
  "description": "Generated by nodejs-quickstart",
  "main": "<% if (language === 'TypeScript') { %>dist/index.js<% } else { %>src/index.js<% } %>",
  "scripts": {
    "start": "<% if (language === 'TypeScript') { %>node dist/index.js<% } else { %>node src/index.js<% } %>",
    "dev": "<% if (language === 'TypeScript') { %>nodemon --exec ts-node src/index.ts<% } else { %>nodemon src/index.js<% } %>"<% if (language === 'TypeScript') { %>,
    "build": "rimraf dist && tsc"<% } %>
  },
  "dependencies": {
    "express": "^4.18.2",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1"<% if (database === 'MySQL') { %>,
    "mysql2": "^3.6.5"<% } %><% if (database === 'PostgreSQL') { %>,
    "pg": "^8.11.3"<% } %><% if (communication === 'Kafka') { %>,
    "kafkajs": "^2.2.4"<% } %>
  },
  "devDependencies": {
    "nodemon": "^3.0.2"<% if (language === 'TypeScript') { %>,
    "typescript": "^5.3.3",
    "ts-node": "^10.9.2",
    "@types/node": "^20.10.5",
    "@types/express": "^4.17.21",
    "@types/cors": "^2.8.17",
    "@types/dotenv": "^8.2.0"<% if (database === 'PostgreSQL') { %>,
    "@types/pg": "^8.10.9"<% } %>,
    "rimraf": "^5.0.5"<% } %>
  }
}`;
    fs.writeFileSync(templatePath, content, 'utf8');
    console.log('Fixed package.json.ejs');
};

fixPackageJson();
